# Generated by Django 4.2.3 on 2025-07-29 05:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtikelRemajaSehat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('konten', ckeditor_uploader.fields.RichTextUploadingField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='remaja_sehat/')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
