# Generated by Django 4.2.3 on 2025-07-28 14:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titipan_cerita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerita',
            name='konten',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
