# Generated by Django 4.2.3 on 2025-07-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruang_bercerita', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cerita',
            name='email',
        ),
    ]
